name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a7
        cpu_info: cpuinfo/raspberrypi_4b
        commands: |
          uname -a
          grep Model /proc/cpuinfo
          df -h
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip
          sudo apt-get -y clean autoremove
          pip install poetry --break-system-packages
          df -h
          poetry install
          poetry run pytest
